### ISSUE TITLE
Uncontrolled input to controlled error

### ISSUE THREAD

**Issue by yoonwaiyan** [aaronshaf/react-toggle#124]
I have this warning while using react-toggle in my new app.

```
warning.js:33 Warning: A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
```

I've been tinkering for a while to make it work as controller component without this warning sign. The only way the warning sign doesn't display is making it as uncontrolled component using `defaultChecked`,  but user has to double click to switch the toggle on the first time clicking the toggle, subsequently it can be toggled with only one click.  This is the code snippet that was last configured with the warning sign:

```
<Toggle
  icons={false}
  name="enabled"
  checked={values.enabled}
  value="yes"
  className="widget-enabled-toggle"
  onChange={event =>
    setFieldValue('enabled', event.target.checked)
  }
/>
```

Is there anything missing here? The installed React version is 16.3.1 with react-toggle 4.0.2.

**Comment by scottanglr** [comment]
Hi @yoonwaiyan 

This is to do with how React works, rather than React-Toggle. Deep down React-Toggle uses plain `<input/>` components.
I'm assuming that values.enabled is undefined the first time this component is rendered. You can check that by running `console.log(values)` in your render function and checking the console.

`<input value={undefined}/>` will remove the input tag, leaving you just with `<input/>`. If the value tag is missing, this means that React gives the input control over its own value (uncontrolled input).

However, what you're trying to do is make it a controlled value, dictated by what values.enabled has. For this reason you can try one of two things:
- Give value.enabled a value initially
- Write `checked={values.enabled || null}`. This means value always has a set vale and therefore remains a controlled input. 

The React docs point to this article to quickly understand the difference. 
[Controlled vs uncontrolled inputs](https://goshakkk.name/controlled-vs-uncontrolled-inputs-react/)

**Comment by yoonwaiyan** [comment]
@4esa It's not the case of value being `undefined` in this case as I'm very sure my value is defined and provided in API, which was saved in the backend with a default value of `true` (I'm using Rails backend). The warning sign displayed but the toggle is checked.

**Comment by yoonwaiyan** [comment]
@4esa oh now I get what you mean. I've figured out it's actually during the API load that caused the value to be temporary undefined which caused this error. Thanks for the tips!
