### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by aaronshaf** [aaronshaf/react-toggle#2]
After a code review I will publish 1.0

**Comment by vanwagonet** [comment]
It would be nice to simplify the svg (looks like sketch adds extra attributes and transforms), and then make them into components instead of `dangerouslySetInnerHTML`.

Is there a particular reason to `preventDefault` on the click?

TIL: [`element.click()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click)

**Comment by aaronshaf** [comment]
Without the `preventDefault` the "With a <label> wrapper tag" demo does not work. The checkbox ends up being double-clicked and doesn't effectively change state.

**Comment by aaronshaf** [comment]
@thetalecrafter, it's using proper SVG components now: https://github.com/instructure-react/react-toggle/commit/12d5a10c7e64976d9e5eab3fede3f6f00e22f67a

**Comment by aaronshaf** [comment]
Upon click, I could perhaps check the ancestor elements for a `<label>`, and then choose not to manually click the checkbox if one is found.

**Comment by vanwagonet** [comment]
I love the svg components. If the checkbox were styled instead to be transparently covering the entire toggle, you wouldn't need handleClick at all, because any click would be hitting the checkbox. There would be no need for a simulated `click()`, and no need to cancel the original event.

That would mean that consumer are more tied to the provided css, but I'm not that worried about that.
