### ISSUE TITLE
Support for react v15

### ISSUE THREAD

**Issue by thom-nic** [aaronshaf/react-toggle#38]
react-toggle has a runtime dependency on `react-addons-pure-render-mixin@0.14.8` as well as devDependencies on react and react-dom@^0.14.8

**Comment by whs** [comment]
Toggle also trigger a warning in React 15:

Warning: Toggle is changing a uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by ManuelDeLeon** [comment]
I got here by googling "is changing a uncontrolled input of type checkbox to be controlled". The solution is to use `defaultValue` instead of `value`. For example: `<input type="checkbox" defaultValue="New York" />`

`<rant>`
Whoever said React has a small API surface hasn't read the docs. It is full of nuances like this one.
`</rant>`

**Comment by lvnr** [comment]
@ManuelDeLeon by using `defaultValue` instead of `value`, you're basically converting it into a uncontrolled input, which is not really a solution.

Actually, I think most of the people are having this issue in React 15 just because they are initially passing `undefined` into the `value` prop and as soon as they change the value later React throws this warning.

If you pass an initial value when mounting the component, it works normally with no warnings.

**Comment by ManuelDeLeon** [comment]
Thanks for the tip levona. I honestly don't remember the problem I was
having or if I initialized the value with undefined or an empty string.
I'll see if I can reproduce  it.

Either way in my case it's fine to use an uncontrolled element.

**Comment by thom-nic** [comment]
I think this can be closed.  react-toggle works fine under react v15 now.
